### ISSUE TITLE
Possible to make it synchronous for testing?

### ISSUE THREAD

**Issue by kentcdodds** [stefanpenner/es6-promise#45]
It's really nice to deal with synchronous code in a testing context. How difficult do you think it would be to make it possible to mock out a backend and make the api synchronous?

**Comment by anatoliyarkhipov** [comment]
What's the reason to make it impossible to resolve the promise synchronously? We have a scenario where user can copy to clipboard data that doesn't exist on client and must be requested from server. The only possible way to deal with security clipboard restrictions in this scenario is to make a sync request. But we can't use promises for that because they cannot be resolved synchronously.

**Comment by stefanpenner** [comment]
Forcing all promises to resolve synchronously changes the program. The problem is often referred to as zalgo, read
More about it in this blog post: http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony

There is something I am an advocate for and that is the ability to synchronously inspect a promise via some power user API. Unfortunately it is not something specified yet although someday it may be, and this particular library aims to remain reasonably aligned with the spec
